### ISSUE TITLE
Structure of the Model.h file

### ISSUE THREAD

**Issue by Alessandro-Trasatti** [Alessandro-Trasatti/Heston_Simulation_Project_repo#1]
@ValentinParavy 
Two of things need to be addressed:
1.  Do we need the BlackScholesModel class? Otherwise we delete it - **TO BE DISCUSSED**.
2. The structure of the HestonModel class is **not** ok imo. We can define the HestonModel class as a derived class from Model. Note that, implicitly, you seem to be using the Heston Model class as a derived class of Model. For example, in the parameter constructor you call the parameter constructor of the Model class which is inaccessible in the present version of the code. The same type of mistake is done later (see the copy constructor, the assignment operator etc.). Moreover, you override methods which does not make any sense if the class is not derived. Note, the derivation has to be done thinking to the Heston model as a bidimensionale case of the general case, i.e. $(S_t,V_t)_t$ (right?!)- **TO BE DISCUSSED AND CHANGED**.

**Comment by ValentinParavy** [comment]
1 No we don't this class indeed, we can delete it
2 I don't understand, HestonModel was indeed defined as a derived class of Model (see history of the code)
